#Config file for alacritty, will take effect at save.

import = [
	"~/.config/alacritty/themes/themes/ayu_dark.toml"#replace <theme>.toml with your desired theme, found at path.
]

[font]
size = 12.0

[font.bold]
#family = "Mononoki Nerd Font"
family = "Nimbus Mono PS"
style = "Bold"
[font.bold_italic]
#family = "Mononoki Nerd Font"
family = "Nimbus Mono PS"
style = "Bold Italic"
[font.italic]
#family = "Mononoki Nerd Font"
family = "Nimbus Mono PS"
style = "Italic"
[font.normal]
#family = "Mononoki Nerd Font"
family = "Nimbus Mono PS"
style = "Regular"

